apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-ugwr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-ugwr
    app.kubernetes.io/part-of: build-suite-test-application-ddgg
  name: test-annotations-ugwr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-ugwr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-ugwr
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-aklj-tenant/build-suite-test-application-ddgg/test-annotations-ugwr@sha256:ae482121cc616906415f7683bc161d42510336027599589dac78aabc58d2f311
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
